### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by tommyturkijevic** [esbencarlsen/NCrawler#1]
Hi esben,

I saw there was another NCrawler in nuget, but it is a copy of your original project. ? Is this more stable than the one on in nuget.

Do you have any examples on how to make  crawler and do a crawl ?

Tommy

**Comment by esbencarlsen** [comment]
Hi

There is a copy of the old project in the v3 branch: https://github.com/esbencarlsen/NCrawler/tree/v3. I think there are several examples in the old project. The one in nuget is not mine, I think is based on the v3 branch.
I do not yet have anything more mature in the new project (v4)

Esben

**Comment by tommyturkijevic** [comment]
Okay, was looking at the v4 and i really liked the way a crawl i setup. Where do I add if i do not want the crawl to go after external Urls ? Do I have to setup a own PipelineStep for this ?
Thanks for you quick reply..

**Comment by esbencarlsen** [comment]
Please keep in mind that the project is still very much alpha.

It will do that by default. Its only restricted to keep within seed host domain by calling the WhereHostInCrawlSeed method on the CrawlerConfiguration instance.

From the NCrawler.Console project:

new CrawlerConfiguration()
				.CrawlSeed(url)
				.RemoveDuplicates()
				.WhereHostInCrawlSeed()   __<-- This one__
				.Robots()
				.Download(Environment.ProcessorCount * 3)
				.LogDownloadTime()
				.HtmlProcessor()
				.LogExceptions()
				.Run();

**Comment by tommyturkijevic** [comment]
Thanks, I will keep that in mind I will do some testing with the project and if i find anything i will let you know..
Once again thanks..
