### ISSUE TITLE
Question about Regex

### ISSUE THREAD

**Issue by tommyturkijevic** [esbencarlsen/NCrawler#2]
Hi Espen,
How does Regex work when I don't want to include or process pages that ends witj #body  or .xls for instance.
Regards
Tommy

**Comment by esbencarlsen** [comment]
Hi Tommy

For matching urls try something like:

new CrawlerConfiguration()
	.CrawlSeed(url)
	.UrlRegexFilter(new Regex("your regex here"))
	.Run();

for matching some HTML element you must add a processing step after HTML itself has been processed for example something like:

new CrawlerConfiguration()
	.CrawlSeed(url)
	.HtmlProcessor()
	.Where((crawler, bag) =>
	{
		HtmlDocument htmlDocument = (HtmlDocument) bag["HtmlDoc"].Value;
		var result = htmlDocument.DocumentNode
			.SelectNodes("some xpath, see HtmlAgilityPack for details")
			.Any();
		return result
	})
	.Run();

BR
Esben

**Comment by tommyturkijevic** [comment]
Hi Espen,


Thank you for your reply, just to make sure, i am not trying to include 
anything, but trying to exclude

urls from being downloaded and parsed. So I have several regular 
expressions so if i for instances add more than one

RegularExpressionFilter like:

.RegexFilter(new Regex("(?!#([A-Za-z\\\\-]{1,})\\w+$|#$|#(\\w+)$)", 
RegexOptions.IgnoreCase | RegexOptions.CultureInvariant | 
RegexOptions.Compiled))

.RegexFilter(new 
Regex("(?!\\.js|\\.css|\\.pdf|\\.jpg|\\.gif|\\.axd|\\.png|\\.ico|\\.doc|\\.docx|\\.xls|\\.xslx|\\.ppt|\\.pptx|\\.axd|\\:jsessionid*|\\?format=ATOM)", 
RegexOptions.IgnoreCase | RegexOptions.CultureInvariant | 
RegexOptions.Compiled))

Will the last one overwrite the previous one ? What I am trying to 
achive is to filter out all pages i do not need, like files, and alot of 
pages has selfreferencing link with anchor tags that I do not not need 
either.

When going through large sites, i get OutOfMemory errors after 2000 
pages, I suspect it might have something to do with Ncrawler is 
downloading all files, even the binary files and then trying to parse them.

Much appreciated and thank you for your replies.

Tommy Turkijevic




Den 2016-06-09 kl. 22:09, skrev esbencarlsen:
>
> Hi Tommy
>
> For matching urls try something like:
>
> new CrawlerConfiguration()
> .CrawlSeed(url)
> .UrlRegexFilter(new Regex("your regex here"))
> .Run();
>
> for matching some HTML element you must add a processing step after 
> HTML itself has been processed for example something like:
>
> new CrawlerConfiguration()
> .CrawlSeed(url)
> .HtmlProcessor()
> .Where((crawler, bag) =>
> {
> HtmlDocument htmlDocument = (HtmlDocument) bag["HtmlDoc"].Value;
> var result = htmlDocument.DocumentNode
> .SelectNodes("some xpath, see HtmlAgilityPack for details")
> .Any();
> return result
> })
> .Run();
>
> BR
> Esben
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/esbencarlsen/NCrawler/issues/2#issuecomment-225011480>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ABQwrhRON05cu5OCXr13We8db--Nel9Fks5qKHMOgaJpZM4Ix6tH>.
>

-- 
Tommy Turkijevic
Email: tommyt@tommyt.se
Mobile: +46 (0)793498401

**Comment by esbencarlsen** [comment]
Hi

Well by default everything is included. The pipeline acts kind of like a filter, where you filter out stuff.
The pipeline always executes sequentially, and applies the filters in the order that you specify them, like this example:

```
new CrawlerConfiguration()
	.CrawlSeed(url) <- Step 1
	.HtmlProcessor() <- Step 2
	.Filter1() <- Step 3
	.Filter2() <- Step 4
	.Filter3() <- Step 5
	.Run();

```

So if Filter1 returns false, Filter2 and Filter3 are never executed.

2000 pages should be nothing for ncrawler, of course depending on what you do once the content is downloaded. Send me an example that generates OutOfMemory exception, I'll have a look at it, and keep in mind this software library is in alpha state :)

Esben

**Comment by tommyturkijevic** [comment]
Hi Espen, 
Ill gladly send you the code, but do you have an email ? This ends up on GitHub, when I reply to you.tommy

Best regards
Tommy Turkijevic
Mobile: +46 (0)793-498401
Email: tommyt@tommyt.se


Date: Fri, 10 Jun 2016 12:41:33 -0700
